---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freshrss.nginx-name" . }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  {{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "freshrss.selectorLabels-nginx" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.freshrss.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "freshrss.selectorLabels-nginx" . | nindent 8 }}
    spec:
      {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "freshrss.nginx-name" . }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
              {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image:  "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.nginx.resources.app | nindent 12 }}
          volumeMounts:
            - name: {{ include "freshrss.nginx-name" . }}-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
            - name: {{ include "freshrss.nginx-name" . }}-data
              mountPath: /app
              readOnly: true
            - name: {{ include "freshrss.nginx-name" . }}-tmp
              mountPath: /tmp
      volumes:
      - name: {{ include "freshrss.nginx-name" . }}-conf
        configMap:
          name: {{ include "freshrss.nginx-name" . }}-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: {{ include "freshrss.nginx-name" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "freshrss.nginx-name" . }}-data
      - name: {{ include "freshrss.nginx-name" . }}-tmp
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.nginx.tmpStorage }}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
