---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.nginx-name" . }}-data
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.nginx.storage.nginx.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.nginx.storage.nginx.size }}