---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshrss.fullname" . }}-admin-user-creation
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
data:
  freshrss-admin-user-creation.sh: |
    cd /app
    if [ ! -f "/app/data/config.php" ]; then
      ./cli/prepare.php
      {{- if eq .Values.freshrss.setting.database.type "sqlite" }}
      ./cli/do-install.php \
        --default_user "$FRESHRSS_USERNAME" \
        --auth_type form \
        --environment production \
        --language {{ .Values.freshrss.setting.language }} \
        --title {{ .Values.freshrss.setting.title }} \
        --base_url {{ .Values.freshrss.setting.base_url }} \
        --db-type sqlite \
        {{ if .Values.freshrss.setting.allow_robots }}--allow_robots \{{ end }}
        {{ if .Values.freshrss.setting.allow_anonymous }}--allow_anonymous \{{ end }}
        {{ if .Values.freshrss.setting.allow_anonymous_refresh }}--allow_anonymous_refresh \{{ end }}
        {{ if .Values.freshrss.setting.api_enabled }}--api_enabled \{{ end }}
      {{ else if eq .Values.freshrss.setting.database.type "postgres" }}
      ./cli/do-install.php 
        --default_user "$FRESHRSS_USERNAME" \
        --auth_type form \
        --environment production \
        --language {{ .Values.freshrss.setting.language }} \
        --title {{ .Values.freshrss.setting.title }} \
        --base_url {{ .Values.freshrss.setting.base_url }} \
        --db-type pgsql \
        --db-host $POSTGRES_HOST \
        --db-user $POSTGRES_USER \
        --db-password $POSTGRES_PASSWORD \
        --db-base $POSTGRES_DB \
        --db-prefix {{ .Values.freshrss.setting.database.dbprefix }} \ 
        --disable_update \
        {{ if .Values.freshrss.setting.allow_robots }}--allow_robots \{{ end }}
        {{ if .Values.freshrss.setting.allow_anonymous }}--allow_anonymous \{{ end }}
        {{ if .Values.freshrss.setting.allow_anonymous_refresh }}--allow_anonymous_refresh \{{ end }}
        {{ if .Values.freshrss.setting.api_enabled }}--api_enabled \{{ end }}
      {{ else if eq .Values.freshrss.setting.database.type "mysql" }}
      ./cli/do-install.php \
        --default_user "$FRESHRSS_USERNAME" \
        --auth_type form \
        --environment production \
        --language {{ .Values.freshrss.setting.language }} \
        --title {{ .Values.freshrss.setting.title }} \
        --base_url {{ .Values.freshrss.setting.base_url }} \
        --db-type mysql \
        --db-host $MYSQL_HOST \
        --db-user $MYSQL_USER \
        --db-password $MYSQL_PASSWORD \
        --db-base $MYSQL_DB \
        --db-prefix {{ .Values.freshrss.setting.database.dbprefix }} \ 
        --disable_update \
        {{ if .Values.freshrss.setting.allow_robots }}--allow_robots \{{ end }}
        {{ if .Values.freshrss.setting.allow_anonymous }}--allow_anonymous \{{ end }}
        {{ if .Values.freshrss.setting.allow_anonymous_refresh }}--allow_anonymous_refresh \{{ end }}
        {{ if .Values.freshrss.setting.api_enabled }}--api_enabled \{{ end }}
      {{- end -}}
      ./cli/create-user.php --user "$FRESHRSS_USERNAME" --password "$FRESHRSS_PASSWORD"
    else
      ./cli/reconfigure.php
    fi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshrss.fullname" . }}-php-timezone
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
data:
  timezone.ini: |
    [PHP]
    date.timezone = "{{ .Values.freshrss.timezone }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshrss.fullname" . }}-nginx-conf
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 8080;
      server_name _;
      root /app/p/;
      index index.php index.html index.htm;
      location ~ ^.+?\.php(/.*)?$ {
        fastcgi_pass {{ include "freshrss.fullname" . }}-fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        # By default, the variable PATH_INFO is not set under PHP-FPM
        # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
        # NOTE: the separate $path_info variable is required. For more details, see:
        # https://trac.nginx.org/nginx/ticket/321
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
      location / {
        try_files $uri $uri/ index.php;
      }
    }