---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.fullname" . }}-data
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.freshrss.storage.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.freshrss.storage.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.fullname" . }}-extensions
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.freshrss.storage.extensions.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.freshrss.storage.extensions.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.fullname" . }}-nginx-data
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.nginx.storage.nginx.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.nginx.storage.nginx.size }}