---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "freshrss.fullname" . }}"
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
type: Opaque
stringData:
  userName: {{ .Values.freshrss.setting.admin.user }}
  userPassword: {{ .Values.freshrss.setting.admin.password }}
  {{- if or (eq .Values.freshrss.setting.database.type "postgres") (eq .Values.freshrss.setting.database.type "mysql") }}
  dbHost: {{ .Values.freshrss.setting.database.host }}
  dbUser: {{ .Values.freshrss.setting.database.user }}
  dbPassword: {{ .Values.freshrss.setting.database.password }}
  dbName: {{ .Values.freshrss.setting.database.dbname }}
  dbPrefix: {{ .Values.freshrss.setting.database.dbprefix | default "app_" }}
  {{- end -}}