---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "freshrss.fullname" . }}"
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
type: Opaque
stringData:
  userName: {{ .Values.freshrss.setting.admin.user }}
  userPassword: {{ .Values.freshrss.setting.admin.password }}