--- 
jobs: 
  lint-docker: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:current"
      resource_class: medium
    steps: 
      - 
        checkout: 
          path: ~/app
      -
        run:
          command: |
            sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v<< pipeline.parameters.hadolint_version >>/hadolint-Linux-x86_64
            sudo chmod +x /usr/local/bin/hadolint
          name: Install Dependencies
      -
        run:
          command: |
            cd ~/app/docker
            /usr/local/bin/hadolint --ignore DL3018 --ignore SC2086 --ignore SC3045 Dockerfile
          name: Lint Dockerfile
    working_directory: ~/app
  lint-helm: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:current"
      resource_class: medium
    steps: 
      - 
        checkout: 
          path: ~/app
      -
        run:
          command: |
            wget https://get.helm.sh/helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz
            tar xvf helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin
            rm -r helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz linux-amd64
          name: Install Dependencies
      -
        run:
          command: |
            cd ~/app/helm
            helm lint
          name: Lint Helm Chart
    working_directory: ~/app
  build-docker: 
    #machine: 
    #  docker_layer_caching: true
    #  image: "ubuntu-2004:current"
    #  resource_class: large
    docker:
      - image: cimg/base:stable
    steps: 
      - setup_remote_docker:
          version: 20.10.14
      - 
        checkout: 
          path: ~/app
      -
        run:
          command: |
            sudo apt-get update
            sudo apt-get -y install binfmt-support qemu-user-static
          name: Install Dependencies
      - 
        run: 
          command: |
            export BUILDKIT_PROGRESS=plain
            cd docker
            export LATEST_VERSION=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/FreshRSS/FreshRSS/releases | jq -r '.[] | select(.prerelease==false) | .tag_name' | sort -V | tail -n1 | cut -d "v" -f 2)
            docker context create builder
            docker buildx create builder
            docker buildx create --use
            docker buildx build --ulimit nofile=1024000 -t ghcr.io/iloveyatoo/freshrss:latest -t ghcr.io/iloveyatoo/freshrss:$LATEST_VERSION-<< pipeline.parameters.revision >> --build-arg APP_VER=$LATEST_VERSION --platform linux/arm64 .
            docker save -o image.tar ghcr.io/iloveyatoo/freshrss:$LATEST_VERSION-<< pipeline.parameters.revision >>
            echo "LATEST_VERSION=$LATEST_VERSION" > env
          name: "Build Docker Image"
      - save_cache:
          key: docker-{{ .Revision }}
          paths:
            - ~/app/docker
    working_directory: ~/app
  build-helm: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:current"
      resource_class: medium
    steps:
      - 
        checkout: 
          path: ~/app
      -
        run:
          command: |
            pip3 install yq
            wget https://get.helm.sh/helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz
            tar xvf helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin
            rm -r helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz linux-amd64
          name: Install Dependencies
      - 
        run: 
          command: |
            cd helm
            export CHART_NAME=$(yq -r .name Chart.yaml)
            export CHART_VERSION=$(yq -r .version Chart.yaml)
            export CHART_TGZ="$CHART_NAME-$CHART_VERSION.tgz"
            mkdir ~/helm_package
            cd ~/helm_package
            helm package ~/app/helm/
            echo "CHART_NAME=$CHART_NAME" > env
            echo "CHART_VERSION=$CHART_VERSION" >> env
            echo "CHART_TGZ=$CHART_TGZ" >> env
          name: "Build Helm Chart"
      - save_cache:
          key: helm-{{ .Revision }}
          paths:
            - ~/helm_package
            - ~/app/helm
    working_directory: ~/app
  deploy-docker: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:current"
      resource_class: medium
    steps: 
      - restore_cache:
          key: docker-{{ .Revision }}
      - 
        run: 
          command: "echo \"$GITHUB_TOKEN\" | docker login --username \"ILoveYaToo\" --password-stdin ghcr.io\n"
          name: "Login to Docker Repo"
      -
        run:
          command: |
            cd ~/app/docker
            source ~/app/docker/env
            docker load -i image.tar
            export GITHUB_API_TOKEN=$(curl -u ILoveYaToo:$GITHUB_TOKEN https://ghcr.io/token\?scope\="repository:<repository/path>:pull" | jq -r .token)
            if [ $(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $GITHUB_API_TOKEN" https://ghcr.io/v2/iloveyatoo/freshrss/manifests/$LATEST_VERSION-<< pipeline.parameters.revision >>) == "404" ]
            then
              docker push ghcr.io/iloveyatoo/freshrss:latest
              docker push ghcr.io/iloveyatoo/freshrss:$LATEST_VERSION-<< pipeline.parameters.revision >>
            else
              echo "Docker Image exists, upload is not required"
            fi
          name: "Upload Docker Image"
    working_directory: ~/app
  deploy-helm: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:current"
      resource_class: medium
    steps: 
      - restore_cache:
          key: helm-{{ .Revision }}
      -
        run:
          command: |
            wget https://get.helm.sh/helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz
            tar xvf helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin
            rm -r helm-v<< pipeline.parameters.helm_version >>-linux-amd64.tar.gz linux-amd64
          name: Install Dependencies
      - 
        run:
          command: |
            cd ~/helm_package
            source ~/helm_package/env
            if [[ $(curl -s -o /dev/null -w "%{http_code}" https://storage.bunnycdn.com/iloveyatoo-helm/$CHART_TGZ --header 'Accept: */*' --header "AccessKey: $BUNNY_STORAGE_HELM_KEY") = 200 ]]
            then
              echo "Helm package exists, upload is not required"
            else
              curl --request GET --url https://storage.bunnycdn.com/iloveyatoo-helm/index.yaml --header 'Accept: */*' --header 'Content-Type: application/octet-stream' --header "AccessKey: $BUNNY_STORAGE_HELM_KEY" -o index.yaml
              helm repo index ~/helm_package --merge index.yaml
              curl --request PUT --url https://storage.bunnycdn.com/iloveyatoo-helm/index.yaml --data-binary @index.yaml --header 'Content-Type: application/octet-stream' --header "AccessKey: $BUNNY_STORAGE_HELM_KEY"
              curl --request PUT --url https://storage.bunnycdn.com/iloveyatoo-helm/$CHART_TGZ --data-binary @$CHART_TGZ --header 'Content-Type: application/octet-stream' --header "AccessKey: $BUNNY_STORAGE_HELM_KEY"
            fi
          name: "Upload Helm Chart"
    working_directory: ~/app
version: 2.1
parameters:
  revision:
    type: integer
    default: 3
  helm_version:
    type: string
    default: "3.9.0"
  hadolint_version:
    type: string
    default: "2.10.0"
workflows: 
  default: 
    jobs: 
      - lint-docker
      - lint-helm
      - build-docker:
          filters:
            branches:
              only: main
          context: 
            - github
          requires:
            - lint-docker
      - build-helm:
          filters:
            branches:
              only: main
          requires:
            - lint-helm
      - deploy-docker:
          requires:
            - build-docker
          context: 
            - github
          filters:
            branches:
              only: main
      - deploy-helm:
          requires:
            - build-helm
          context: 
            - bunny-storage-helm
          filters:
            branches:
              only: main